import { Wenge } from "../constants/colors";
import MainImage from "../assets/photos/MainImage.png";
import { Black400 } from "../constants/colors";

export const MainPageStyles = {
    componentTitle:{
        fontFamily: 'poppins',
        fontSize: '42px',
        fontWeight: 'semi-bold',
        color: Wenge,
        marginTop: '5%',
    },
    ongListBox: {
        marginLeft: '17%',
        marginRight: '17%',
    },
    mainBox:{
        width: '100%',
        height: '85vh',
        flexDirection: 'column',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
        position: 'relative',
        backgroundImage: `url(${MainImage})`,
        backgroundSize: 'cover',
    },
    mainTypo:{
        color: '#fff',
        fontSize: '54px',
        lineHeight: '32px',
        fontWeight: 800,
        fontFamily: 'Raleway, system-ui, -apple-system, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, Liberation Sans, sans-serif',
        marginTop: '0',
        position: 'absolute',
    },
    boxMainSubBox:{
        flexDirection: 'column',
        color: '#fff',
        textAlign: 'left',
        position: 'absolute',
    },
    mainDescription:{
        fontSize: '22px',
        lineHeight: '32px',
        fontWeight: 500,
        fontFamily: 'Raleway, system-ui, -apple-system, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, Liberation Sans, sans-serif',
    },
    paginationBox:{
        display: "flex",
        justifyContent: "flex-end",
        alignItems: "flex-end",
        marginRight: '6%',
        marginBottom: '10px',
    },
    paginationTypo:{
        fontFamily: 'poppins',
        fontSize: '18px',
        fontWeight: 600,
        marginLeft: '3px',
        color: Black400,
    },
    paper:{
        position: 'relative',
        width: '100%',
        height: '75vh',
        flexDirection: 'column',
        alignItems: 'flex-start', 
        overflow: 'hidden',
        textAlign: 'center',
        marginTop: '3%',
        marginBottom: '3%',
        transition: 'opacity 0.8s ease, background-color 0.8s ease, transform 0.8s ease', // Adjust transition duration
        willChange: 'transform', // Add will-change property
    },
    iconBox:{
        position: 'absolute',
        alignItems: 'left',
        width: '80px',
        height: '80px',
        transition: 'transform 0.8s ease', 
        '&:hover': {
            transform: 'rotate(90deg)', 
        },
    },
    iconTypo:{
        color: '#f9f9f9',
        fontSize: '26px',
        lineHeight: '32px',
        fontWeight: 600,
        fontFamily: 'Inter, system-ui, -apple-system, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, Liberation Sans, sans-serif',
        position: 'absolute',
        width: '271px',
        height: '32px',
        flexDirection: 'column',
        transition: 'transform 0.8s ease', 
    },
    lineBox:{
        position: 'relative',
        left: '960px',
        top: '52px',
        width: '1px',
        maxWidth: '100%',
        height: '618px',
        maxHeight: '100%',
    },
    line:{
        content: '""',
        position: 'absolute',
        top: '0',
        left: '0',
        transformOrigin: '0 0',
        transform: 'rotate(90deg)',
        width: '618px',
        height: '0',
        borderBottom: 'solid 1px #f9f9f9',
    },
    reasonsBox:{
        position: 'absolute',
        left: '748px',
        top: '130px',
        width: '409px',
        height: '58px',
        outline: 'solid 1px #9d6a89',
        outlineOffset: '-1px',
        borderRadius: '15px',
        backgroundColor: '#ee92c2',
    },
    reasonButton:{
        color: '#f9f9f9',
        fontSize: '20px',
        lineHeight: '32px',
        fontWeight: 600,
        fontFamily:
        'Poppins, system-ui, -apple-system, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, Liberation Sans, sans-serif',
        letterSpacing: '0.03em',
        position: 'absolute',
        left: '791px',
        top: '132px',
        width: '338px',
        height: '50px',
        textAlign: 'center',
        alignItems: 'center',
        flexDirection: 'column',
    },
    reasonTypo:{
        color: '#725d68',
        fontSize: '45px',
        lineHeight: '32px',
        fontWeight: 500,
        fontFamily:
        'Poppins, system-ui, -apple-system, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, Liberation Sans, sans-serif',
        position: 'absolute',
        left: '614px',
        top: '56px',
        width: '957px',
        height: 'min-content',
        flexDirection: 'column',
    }
}