name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy Frontend on Self-Hosted Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Transfer Files to Self-Hosted Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: '.'
          target: '/home/hopeshar/frontend'

      - name: Deploy to Self-Hosted Server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/hopeshar/frontend
            rm -f .env
            touch .env
            echo "REACT_APP_API_PORT=${{ secrets.REACT_APP_API_PORT }}" > .env
            echo "REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}" >> .env
            echo "REACT_APP_GOOGLE_CLIENT_SECRET=${{ secrets.REACT_APP_GOOGLE_CLIENT_SECRET }}" >> .env
            echo "REACT_APP_REDIRECT_URI=${{ secrets.REACT_APP_REDIRECT_URI }}" >> .env
            echo "REACT_APP_API_PORT_FE=${{ secrets.REACT_APP_API_PORT_FE }}" >> .env
            echo "PORT=${{ secrets.PORT }}" >> .env
            cd ..
            sudo docker-compose up -d --build
