name: Build and Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Docker Build and Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t andreeaene/hopeshare-frontend:${{ github.sha }} .
          docker tag andreeaene/hopeshare-frontend:${{ github.sha }} andreeaene/hopeshare-frontend:latest
          docker push andreeaene/hopeshare-frontend:${{ github.sha }}
          docker push andreeaene/hopeshare-frontend:latest

      - name: Deploy to Self-Hosted Server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/hopeshar
            echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > .env
            echo "REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}" >> .env
            echo "REACT_APP_GOOGLE_CLIENT_SECRET=${{ secrets.REACT_APP_GOOGLE_CLIENT_SECRET }}" >> .env
            echo "REACT_APP_REDIRECT_URI=${{ secrets.REACT_APP_REDIRECT_URI }}" >> .env
            docker-compose pull
            docker-compose up -d
